import assert from 'node:assert/strict'
import { appendFile, mkdtemp, rm, unlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { withCreatorFingerprint } from '../lib/creator-export.js'
import { doctorPlugin } from '../lib/doctor.js'
import { writeFilesExclusive } from '../lib/files.js'
import { renderGeneratedBundle } from '../lib/templates.js'

function exportValue() {
  return withCreatorFingerprint({
    format: 'dsh-creator-export',
    schemaVersion: 1,
    name: 'doctor-fixture',
    packageName: 'doctor-fixture',
    author: 'Doctor test contributors',
    description: 'A fixture for deterministic Doctor checks.',
    goal: 'Exercise the release catalogue.',
    instructions: 'Return one deterministic result.',
    compatibilityTarget: '0.1.1-rc.2',
    decisions: [],
    unresolvedRisks: [],
    tools: [],
    resources: [],
  })
}

async function generatedFixture() {
  const root = await mkdtemp(join(tmpdir(), 'dsh-developer-doctor-'))
  await writeFilesExclusive(root, renderGeneratedBundle(exportValue()).files)
  return root
}

test('accepts exact generated bytes and blocks post-generation drift', async () => {
  const root = await generatedFixture()
  try {
    const exact = await doctorPlugin(root, {
      runtime: 'skip',
      requireGenerated: true,
    })
    assert.equal(exact.ok, true, JSON.stringify(exact.checks, null, 2))

    await appendFile(join(root, 'README.md'), '\nChanged after generation.\n', 'utf8')
    const changed = await doctorPlugin(root, {
      runtime: 'skip',
      requireGenerated: true,
    })
    assert.equal(changed.ok, false)
    assert.equal(
      changed.checks.find((check) => check.id === 'packaging.reproducible').status,
      'FAIL',
    )
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})

test('treats partial provenance as a blocking integrity failure', async () => {
  const root = await generatedFixture()
  try {
    await unlink(join(root, 'dsh-developer.manifest.json'))
    const report = await doctorPlugin(root, { runtime: 'skip' })
    const check = report.checks.find((candidate) => candidate.id === 'packaging.reproducible')
    assert.equal(check.status, 'FAIL')
    assert.equal(check.blocking, true)
    assert.equal(report.ok, false)
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})

test('requires the declared package entry on the matching DSH row', async () => {
  const root = await generatedFixture()
  try {
    await writeFile(join(root, 'cordis.patch.yml'), [
      '- insert:',
      '    - id: doctor-fixture',
      "      name: 'different-package'",
      '    - id: unrelated-row',
      "      name: 'doctor-fixture'",
      '',
    ].join('\n'), 'utf8')
    const report = await doctorPlugin(root, { runtime: 'skip' })
    assert.equal(report.checks.find((value) => value.id === 'dsh.entrypoint').status, 'FAIL')
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})

test('blocks an incomplete upstream attachment claim for dynamic inject source', async () => {
  const root = await generatedFixture()
  try {
    await writeFile(join(root, 'index.js'), [
      "export const name = 'doctor-fixture'",
      "const required = ['skills']",
      'export const inject = Object.freeze(required)',
      'export async function apply() {}',
      '',
    ].join('\n'), 'utf8')
    const report = await doctorPlugin(root, { runtime: 'skip' })
    const failed = report.checks.find((value) => value.id === 'compatibility.upstream-attachments')
    assert.equal(failed.status, 'FAIL')
    assert.equal(failed.evidence.code, 'UNSCOPED_INJECT_CONTRACT')
    assert.deepEqual(failed.evidence.paths, ['index.js'])
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})
